name: absensi_triple_des_offline
description: "Aplikasi Absensi Offline menggunakan keamanan enkripsi Triple DES berbasis Flutter untuk demo skripsi/tugas akhir."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # QR Code scanning and generation
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

  # Firebase Cloud
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  firebase_database: ^12.1.1
  firebase_storage: ^13.4.1

  # UI & Icons
  cupertino_icons: ^1.0.6
  geolocator: ^14.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
