// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8gBUfjdj3yYRyLiOHFzmWGDRGCaLKoM',
    appId: '1:78141225225:web:b2f78c69a22cd952fcfbd8',
    messagingSenderId: '78141225225',
    projectId: 'siskem-firebase',
    authDomain: 'siskem-firebase.firebaseapp.com',
    storageBucket: 'siskem-firebase.firebasestorage.app',
    measurementId: 'G-DGLX4N0B8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Az8kJzHNeKIYwoIVNUCQhjtxkg5eGJQ',
    appId: '1:78141225225:android:88603fa5219fd740fcfbd8',
    messagingSenderId: '78141225225',
    projectId: 'siskem-firebase',
    storageBucket: 'siskem-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABg0htnWVsSAFpClW1gEEhMHVXOa2r6-U',
    appId: '1:78141225225:ios:cc53fa957e1c848bfcfbd8',
    messagingSenderId: '78141225225',
    projectId: 'siskem-firebase',
    storageBucket: 'siskem-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABg0htnWVsSAFpClW1gEEhMHVXOa2r6-U',
    appId: '1:78141225225:ios:cc53fa957e1c848bfcfbd8',
    messagingSenderId: '78141225225',
    projectId: 'siskem-firebase',
    storageBucket: 'siskem-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn8gBUfjdj3yYRyLiOHFzmWGDRGCaLKoM',
    appId: '1:78141225225:web:4d5023920ffe6fbbfcfbd8',
    messagingSenderId: '78141225225',
    projectId: 'siskem-firebase',
    authDomain: 'siskem-firebase.firebaseapp.com',
    storageBucket: 'siskem-firebase.firebasestorage.app',
    measurementId: 'G-FB7V34G554',
  );
}
